### ISSUE TITLE
having trouble running the geojson extension in JupyterLab

### ISSUE THREAD

**Issue by swatson26** [jupyterlab/jupyter-renderers#101]
Jupyterlab version: 0.31.8
Notebook version: 5.4.0

I installed the plotly extension and was able to run the example successfully in a notebook but I installed the geojson-extension and in a notebook I go to run the example 
`from IPython.display import GeoJSON`
and get
`ImportError: cannot import name GeoJSON`

When I installed the extension I got a bunch of errors but none seemed to be listed serious

`[root@ip-192-168-1-185 lab]# jupyter-labextension install @jupyterlab/geojson-extension
> /usr/local/bin/npm pack @jupyterlab/geojson-extension
jupyterlab-geojson-extension-0.14.4.tgz
> node /usr/local/lib/python2.7/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > mapbox-gl-function@1.3.0: This package has been merged with the 'mapbox-gl-style-spec' package
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > mapbox-gl-supported@1.2.0: This package has been moved to @mapbox/mapbox-gl-supported
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vt-pbf > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vt-pbf > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > unitbezier@0.0.0: This module has moved: switch to @mapbox/unitbezier
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > geojson-rewind > geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
warning @jupyterlab/plotly-extension > plotly.js > ndarray-fill > cwise > static-module > through2 > xtend > object-keys@0.4.0: 
warning @jupyterlab/plotly-extension > plotly.js > color-rgba > color-space > husl@5.0.3: Project renamed to HSLuv
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > mapbox-gl-style-spec > jsonlint-lines-primitives > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
[-/2] ⠐ waiting...
[2/2] ⠐ canvas: '-Goutput_dir=.' ]
[-/2] ⠐ waiting...
[-/2] ⠐ waiting...
warning Error running install script for optional dependency: "/usr/local/share/jupyter/lab/staging/node_modules/canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: /usr/local/share/jupyter/lab/staging/node_modules/canvas\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@9.0.0 | linux | x64\ngyp info spawn /usr/local/bin/python2\ngyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'make',\ngyp info spawn args   '-I',\ngyp info spawn args   '/usr/local/share/jupyter/lab/staging/node_modules/canvas/build/config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/root/.node-gyp/9.0.0/include/node/common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/9.0.0',\ngyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',\ngyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/9.0.0/<(target_arch)/node.lib',\ngyp info spawn args   '-Dmodule_root_dir=/usr/local/share/jupyter/lab/staging/node_modules/canvas',\ngyp info spawn args   '-Dnode_engine=v8',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'build',\ngyp info spawn args   '-Goutput_dir=.' ]\nPackage cairo was not found in the pkg-config search path.\nPerhaps you should add the directory containing `cairo.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'cairo' found\ngyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp\ngyp ERR! configure error \ngyp ERR! stack Error: `gyp` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)\ngyp ERR! stack     at emitTwo (events.js:135:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:224:7)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_procesuccess Saved lockfile.
Done in 72.06s.
> node /usr/local/lib/python2.7/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
Hash: 31977bb08b9ea5a727fe
Version: webpack 2.7.0
Time: 34484ms
`

I checked to ensure the extension was enabled with 
` jupyter-labextension check @jupyterlab/geojson-extension`

and double-checked the page_config.json

**Comment by gnestor** [comment]
The above look like mere npm warnings. It think what you need is: `pip install ipython --upgrade`. The `GeoJSON` display class was added in ipython 6.

**Comment by swatson26** [comment]
I didnt realize this extension had a dependency on python3. Will try and upgrade to ipython 6x

**Comment by gnestor** [comment]
Well the extension doesn't have any Python dependencies, ipython just provides the `GeoJSON` display class which makes rendering GeoJSON more convenient. You could just a define a `GeoJSON` function yourself:

```py
def GeoJSON(data={}):
    bundle = {}
    bundle['application/geo+json'] = {
        'data': data,
        'layout': layout,
    }
    display(bundle, raw=True)
```

**Comment by swatson26** [comment]
thanks workaround

just in case anyone ends up in a similar scenario, I ended up defining the following function
` def GeoJSON(data={}, metadata={}):
    bundle = {
            'application/geo+json': data,
            'text/plain': '<IPython.display.GeoJSON object>'
    }
    metadata = {
        'application/geo+json': metadata
    }
    display(bundle, metadata=metadata, raw=True)`
