### ISSUE TITLE
binary or npm-free distribution?

### ISSUE THREAD

**Issue by bigeagle** [jupyterlab/jupyter-renderers#103]
Hi there,

I am using a server that npm cannot be installed. 
How can I install these extentions?
Is it possible that I somehow build these extentions and then put some bundled static files to some place?

cheers,
justin

**Comment by gnestor** [comment]
@blink1073 What are your thoughts?

**Comment by blink1073** [comment]
Hi @bigeagle, you could build on another machine and then copy the contents of the `Application directory` (given by `jupyter lab paths`) from the network-connected machine to the server `Application directory` location.

**Comment by bigeagle** [comment]
@blink1073 thanks, I'll try this way.

**Comment by domoritz** [comment]
Can this be closed?
