### ISSUE TITLE
Mapbox Certificate problem

### ISSUE THREAD

**Issue by devonyates** [jupyterlab/jupyter-renderers#106]
When i try to install  the plotly extension

jupyter labextension install @jupyterlab/plotly-extension

the installation fails with:

error An unexpected error occurred: "https://github.com/mapbox/mapbox-gl-shaders: unable to get local issuer certificate".

I am behind a proxy, but am able to install other packages no problem.

**Comment by gnestor** [comment]
This looks like a pltoly.js dependency issue: https://github.com/plotly/plotly.js/issues/2104

**Comment by gnestor** [comment]
Can you try this?: https://github.com/nodejs/node/issues/3742#issuecomment-155545828

**Comment by gnestor** [comment]
@devonyates Is this resolved now?

**Comment by devonyates** [comment]
Yes, this is working for me now.  I believe the resolution was related to adding the cert configuration, as indicated in the link you sent.  Sorry I didn't respond sooner, thanks for your attention!
