### ISSUE TITLE
Failed to Install with Anaconda

### ISSUE THREAD

**Issue by jvaldiviezo9** [jupyterlab/jupyter-renderers#109]
Hi! I use the Anaconda Distribution. and I have the following versions
plotly: 2.4.1
jupyter lab: 0.31.10
nodejs: 8.9.3

and I executed the command as in the documentation: jupyter labextension install @jupyterlab/plotly-extension

the output is as follows, this happens in Windows 10 and in macos Sierra

(base) C:\Users\Aristh\Desktop\test>jupyter labextension install @jupyterlab/plotly-extension
> C:\Users\Aristh\Anaconda3\npm.CMD pack @jupyterlab/plotly-extension
jupyterlab-plotly-extension-0.14.4.tgz
> node C:\Users\Aristh\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > mapbox-gl-function@1.3.0: This package has been merged with the 'mapbox-gl-style-spec' package
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > mapbox-gl-supported@1.2.0: This package has been moved to @mapbox/mapbox-gl-supported
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > unitbezier@0.0.0: This module has moved: switch to @mapbox/unitbezier
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vector-tile > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > vt-pbf > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning @jupyterlab/plotly-extension > plotly.js > ndarray-fill > cwise > static-module > through2 > xtend > object-keys@0.4.0:
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
warning @jupyterlab/plotly-extension > plotly.js > color-rgba > color-space > husl@5.0.3: Project renamed to HSLuv
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > geojson-rewind > geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> node C:\Users\Aristh\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
'webpack' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Is there a problem with the installation or something I'm doing wrong?

**Comment by blink1073** [comment]
I think the problem is that one of the dependencies is on github: `error Couldn't find the binary git`.  Do you have `git` installed?

**Comment by jvaldiviezo9** [comment]
@blink1073 Thanks!! I installed Git and then reinstalled Anaconda and that solve the problem.
