### ISSUE TITLE
Plotly animations not working in JLab

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyter-renderers#118]
This is a fresh issue spun [off an old one in the plotly repo](https://github.com/plotly/plotly.py/issues/948) to focus the discussion on Lab-specific questions.  Key points from that issue copied here for reference.

Assuming that the plotly extension is installed from [jupyter-renderers](https://github.com/jupyterlab/jupyter-renderers), with 

```
jupyter labextension install @jupyterlab/plotly-extension
```

Then, on JupyterLab 0.31.12, this code:

```python
import plotly.offline as py
py.init_notebook_mode(connected=False)  # This line is unnecessary in JLab, needed in classic

figure = {'data': [{'x': [0, 1], 'y': [0, 1], 'z': [0, 1], 'type': 'scatter3d'}],
          'layout': {'scene': {'xaxis': {'range': [0, 5], 'autorange': False},
                               'yaxis': {'range': [0, 5], 'autorange': False},
                               'zaxis': {'range': [0, 5], 'autorange': False}},
                     'updatemenus': [{'type': 'buttons',
                                      'buttons': [{'label': 'Play',
                                                   'method': 'animate',
                                                   'args': [None]}]}]
                    },
          'frames': [{'data': [{'x': [1, 2], 'y': [1, 2], 'z': [0, 3], 'type': 'scatter3d'}]},
                     {'data': [{'x': [1, 4], 'y': [1, 4], 'z': [0, 3], 'type': 'scatter3d'}]},
                     {'data': [{'x': [3, 4], 'y': [3, 4], 'z': [0, 3], 'type': 'scatter3d'}]}]
         }

py.iplot(figure)
```

produces a static image with a non-functioning "Play" button:

![image](https://user-images.githubusercontent.com/57394/37577715-038f0b7a-2af1-11e8-800a-72bdab3fba7c.png)

and this error message in the console, just as @jasongrout suggested:

![image](https://user-images.githubusercontent.com/57394/37577719-134e7c6c-2af1-11e8-8153-044826aec688.png)

If the same notebook is opened in Classic (even within the same session), then the Play button animates as expected.

cc @jasongrout @gnestor to continue discussion here.

**Comment by johncomposed** [comment]
Note they also handle config separately. See https://plot.ly/python/configuration-options/.

At the bottom of they have the full api:
```python
plot(figure_or_data, show_link=True, link_text='Export to plot.ly', validate=True, output_type='file', include_plotlyjs=True, filename='temp-plot.html', auto_open=True, image=None, image_filename='plot_image', image_width=800, image_height=600, config=None)

"""
   Create a plotly graph locally as an HTML document or string.
    
    Example:
    ```
    from plotly.offline import plot
    import plotly.graph_objs as go
    
    plot([go.Scatter(x=[1, 2, 3], y=[3, 2, 6])], filename='my-graph.html')
    # We can also download an image of the plot by setting the image parameter
    # to the image format we want
    plot([go.Scatter(x=[1, 2, 3], y=[3, 2, 6])], filename='my-graph.html'
         image='jpeg')
    ```
    More examples below.
    
    figure_or_data -- a plotly.graph_objs.Figure or plotly.graph_objs.Data or
                      dict or list that describes a Plotly graph.
                      See https://plot.ly/python/ for examples of
                      graph descriptions.
    
    Keyword arguments:
    show_link (default=True) -- display a link in the bottom-right corner of
        of the chart that will export the chart to Plotly Cloud or
        Plotly Enterprise
    link_text (default='Export to plot.ly') -- the text of export link
    validate (default=True) -- validate that all of the keys in the figure
        are valid? omit if your version of plotly.js has become outdated
        with your version of graph_reference.json or if you need to include
        extra, unnecessary keys in your figure.
    output_type ('file' | 'div' - default 'file') -- if 'file', then
        the graph is saved as a standalone HTML file and `plot`
        returns None.
        If 'div', then `plot` returns a string that just contains the
        HTML <div> that contains the graph and the script to generate the
        graph.
        Use 'file' if you want to save and view a single graph at a time
        in a standalone HTML file.
        Use 'div' if you are embedding these graphs in an HTML file with
        other graphs or HTML markup, like a HTML report or an website.
    include_plotlyjs (default=True) -- If True, include the plotly.js
        source code in the output file or string.
        Set as False if your HTML file already contains a copy of the plotly.js
        library.
    filename (default='temp-plot.html') -- The local filename to save the
        outputted chart to. If the filename already exists, it will be
        overwritten. This argument only applies if `output_type` is 'file'.
    auto_open (default=True) -- If True, open the saved file in a
        web browser after saving.
        This argument only applies if `output_type` is 'file'.
    image (default=None |'png' |'jpeg' |'svg' |'webp') -- This parameter sets
        the format of the image to be downloaded, if we choose to download an
        image. This parameter has a default value of None indicating that no
        image should be downloaded. Please note: for higher resolution images
        and more export options, consider making requests to our image servers.
        Type: `help(py.image)` for more details.
    image_filename (default='plot_image') -- Sets the name of the file your
        image will be saved to. The extension should not be included.
    image_height (default=600) -- Specifies the height of the image in `px`.
    image_width (default=800) -- Specifies the width of the image in `px`.
    config (default=None) -- Plot view options dictionary. Keyword arguments
        `show_link` and `link_text` set the associated options in this
        dictionary if it doesn't contain them already.

"""
```

I was just running into to this so thought I'd give a heads up.

**Comment by gnestor** [comment]
@johncomposed It looks like `config` doesn't get included in the mime bundle (output), so plotly-extension doesn't have access to `config` ☹️

https://github.com/plotly/plotly.py/blob/master/plotly/offline/offline.py#L348

If you need config support, then I suggest creating an issue on the plotly.py repo. The gist of the issue is that JupyterLab doesn't support inline Javascript in `text/html` outputs or `application/javascript` outputs like the classic notebook did. Therefore, plotly.py's init_notebook_mode` doesn't work in JupyterLab. JupyterLab extensions such as plotly-extension are meant to be solid solutions to this problem vs. the many hacks that were required with the classic notebook. Although JupyterLab is quite new, it is the future Jupyter client and the classic notebook with be deprecated at some point, so plotly.py should provide proper support for rendering in JupyterLab. `plotly.offline.iplot` works for the most part, but config is included in the mime bundle and as a result cannot be used by JupyterLab extensions.
