### ISSUE TITLE
development environment

### ISSUE THREAD

**Issue by mjmdavis** [jupyterlab/jupyter-renderers#120]
Can anyone outline a way to create a virtual environment for development work on the labextensions?

I'm having some trouble separating development and production on my workstation.

**Comment by ian-r-rose** [comment]
@mjmdavis I typically use conda virtual environments for this purpose (though you should also be able to use virtualenv). Their documentation is [here](https://conda.io/docs/user-guide/tasks/manage-environments.html). Do you have a more specific question about labextensions?

**Comment by gnestor** [comment]
Simply running `jupyter labextension install @jupyterlab/plotly-extension` will get you the production version and `jupyter labextension link packages/plotly-extension` will get you the dev version
