### ISSUE TITLE
Support for plotly widgets?

### ISSUE THREAD

**Issue by timkpaine** [jupyterlab/jupyter-renderers#128]
[Python Code](https://github.com/plotly/plotly.py/blob/master/plotly/widgets/graph_widget.py)
[Javascript Code](https://github.com/plotly/plotly.py/blob/master/plotly/package_data/graphWidget.js)

Following [these (quite out-of-date) notebooks](https://moderndata.plot.ly/widgets-in-ipython-notebook-and-plotly/) for reference.

**Comment by gnestor** [comment]
This would be awesome but I think that it would require a new extension (I don't think it would gracefully fit into the plotly-extension). Check out https://github.com/plotly/jupyterlab-chart-editor which is a new JupyterLab extension for creating plotly charts without code.

**Comment by gnestor** [comment]
@timkpaine Looking at this again, it looks like it should work in JupyterLab. However, I just tried out some of their example notebooks and it looks like both the `GraphWidget` code in plotly.py and the example notebooks were written about 4 years ago, when `widgets` were still in the ipython library. Now widgets have moved to `ipywidgets` and many APIs have changed. 

With that said, there are still ways that ipywidgets can work with plotly charts (using plotly-extension). 

Here is an example notebook: https://gist.github.com/gnestor/224fd455405bceddbb26aec52420af17

Here's a GIF:

![](http://g.recordit.co/tTL9zUHsk9.gif)

**Comment by dhirschfeld** [comment]
IIUC there is currently ongoing work to integrate plotly with ipywidgets:
https://github.com/plotly/plotly.py/pull/942

**Comment by timkpaine** [comment]
@gnestor @dhirschfeld much obliged, this will do very nicely!!

**Comment by gnestor** [comment]
Thanks @timkpaine! Let's continue conversation over there...
