### ISSUE TITLE
Installation failed: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by taxus13** [jupyterlab/jupyter-renderers#151]
Hi, 
I am trying to install the plotly extension, but the installation fails due to JS heap out of memory. See the full output here: https://gist.github.com/taxus13/361a929172879f1a7faa3524c1c42fe2

Note that the installtion process did not terminate, the GC output seems to repeat.

My System:
Windows 10x64
Python 3.6.5
Node.js 8.11.3

Please let me now if you need further information.

**Comment by gnestor** [comment]
This is a known issue with jupyterlab's build process. See https://github.com/jupyterlab/jupyterlab/issues/4325 for more info. The workaround is to run `export NODE_OPTIONS=--max-old-space-size=4096` in the terminal before `jupyter lab` or `jupyter lab build` or you can pass it as an environment variable to the command: `NODE_OPTIONS=--max-old-space-size=4096 jupyter lab`.
