### ISSUE TITLE
JSON not rendering

### ISSUE THREAD

**Issue by TomGoBravo** [jupyterlab/jupyter-renderers#169]
I'm trying to use the JSON rendering. I made a notebook cell containing
```
from IPython.display import JSON
data = {"foo": {"bar": "baz"}, "a": 1}
JSON(data)
```
and the output is
```
<IPython.core.display.JSON object>
```

Looking at https://github.com/jupyterlab/jupyter-renderers/blob/master/notebooks/json-extension.ipynb as rendered in chrome I see the same output (literal strings "<IPython.core.display.JSON object>") but I was expecting to see something like https://www.youtube.com/watch?v=FRj1r7-7kiQ (collapsible tree for the nested dictionaries).

**Comment by dbabbitt** [comment]
You need to restart the JupyterLab server after you have run `jupyter labextension install @jupyterlab/geojson-extension`

**Comment by damodeo** [comment]
Hello,
I'm trying to use The Littlest JupyterHub on AWS, I have the same issue "<IPython.core.display.JSON object>". I launched the "sudo -E jupyter labextension install @jupyterlab/geojson-extension" but the error is not fixed.

Any idea?

**Comment by gnestor** [comment]
Are you using JupyterLab? JupyterLab comes with @jupyterlab/json-extension installed by default. @upyterlab/geojson-extension is for rendering geojson, which is different.
