### ISSUE TITLE
can't install, unknown vega module

### ISSUE THREAD

**Issue by neurotensin** [jupyterlab/jupyter-renderers#172]
Hi,

Someone else reported this on stackover flow using Windows (I am using ubuntu bionic), but I had the same problem. I have tried a load of things, so I'd appreciate someone weighing in.

I am running  a docker jupyter lab==0.34.0 , node==v8.10.0, python==3.6.3, conda == 4.5.11

https://stackoverflow.com/questions/53646715/error-with-install-plotly-extention-for-jupyter-lab

Any ideas? With the 1000's of dependencies pulled in, I'm amazed it stopped here!

NT.

**Comment by domoritz** [comment]
I don't think this is related to Vega, btw.

**Comment by domoritz** [comment]
Can this be closed?

**Comment by gnestor** [comment]
Closing for now...
