### ISSUE TITLE
Does this include jupyterlab_json?

### ISSUE THREAD

**Issue by deeplook** [jupyterlab/jupyter-renderers#182]
The https://github.com/jupyter-attic/jupyterlab_json repo claims it has been moved into this one. Except I cannot see it. Should it be here? Or elsewhere? Any pointers welcome.

**Comment by blink1073** [comment]
Hi @deeplook, it was absorbed into Jupyterlab core: https://github.com/jupyterlab/jupyterlab/tree/master/packages/json-extension
