### ISSUE TITLE
GeoJSON - information for a point?

### ISSUE THREAD

**Issue by consideRatio** [jupyterlab/jupyter-renderers#187]
Is GeoJSON supposed to show information if click / hover over a point?

For example, in jupyterlab/jupyterlab-demo, there is [a .geojson file](https://github.com/jupyterlab/jupyterlab-demo/blob/master/data/Museums_in_DC.geojson) showing museum map locations and there is a lot of information about them, but from the mapview it is hidden. Is my GeoJSON extension failing, or is it not something that is implemented?

I notice that on GitHub, the geojson previewer allows for viewing information about the point on the map.

# GitHub preview of the file

![github-geojson-preview](https://user-images.githubusercontent.com/3837114/55574182-1d0b1380-570c-11e9-9678-d78f098503a2.gif)

# My GeoJSON extension installation in action
![geojson-point-info-fail](https://user-images.githubusercontent.com/3837114/55573878-5d1dc680-570b-11e9-8ae5-b444e19c32f1.gif)

**Comment by gnestor** [comment]
The [implementation is pretty simple](https://github.com/jupyterlab/jupyter-renderers/blob/master/packages/geojson-extension/src/index.ts) so I think it's just not implemented (unless all of that can be encoded in the GeoJSON and leaflet just knows what to do with it).

**Comment by adriantre** [comment]
I think changing [this line in the code](https://github.com/jupyterlab/jupyter-renderers/blob/a3b7ceafd806f884c64974fadc83af88b4f6d522/packages/geojson-extension/src/index.ts#L112) to the below snipped should solve this issue:
```
this._geoJSONLayer= leaflet.geoJSON(data, {
    onEachFeature: function (feature, layer) {
  if (feature.properties) {
    var popupContent = '<table>';
    for (var p in feature.properties) {
      popupContent += '<tr><td>' + p + ':</td><td><b>' + feature.properties[p] + '</b></td></tr>';
    }
    popupContent += '</table>';
    layer.bindPopup(popupContent);
  }
}
}).addTo(this._map);
```

**Comment by ian-r-rose** [comment]
That looks good to me @adriantre, care to make a PR?

**Comment by adriantre** [comment]
Done!
