### ISSUE TITLE
compile error json_renderer

### ISSUE THREAD

**Issue by tkinz27** [jupyterlab/jupyter-renderers#19]
Currently having some trouble compiling the json renderer

```
> tsc

src/component.tsx(25,14): error TS2415: Class 'Component' incorrectly extends base class 'Component<IProps, IState>'.
  Types of property 'state' are incompatible.
    Type '{ filter: string; }' has no properties in common with type 'Readonly<IState>'.
```

**Comment by gnestor** [comment]
There's an issue with typescript 2.4 and the react type declarations (I think). Downgrading typescript to 2.3 resolved this for me.

```
git pull jupyterlab master
lerna clean
npm install
npm run build
```

If you're still running into issues, trying deleting the package-lock.json at the project root and then the steps above again.

**Comment by tkinz27** [comment]
Thanks, verified it worked for me.
