### ISSUE TITLE
Deprecate @jupyterlab/plotly-extension

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyter-renderers#206]
> The @jupyterlab/plotly-extension extension for rendering plotly figures in JupyterLab has been replaced by a new jupyterlab-plotly extension that will now be maintained and updated as a part of the plotly.py project.

https://community.plot.ly/t/introducing-plotly-py-4-0-0rc1/25639

@jonmmease Is it time to deprecate @jupyterlab/plotly-extension? If so, what should the steps be? Deprecation message on npm and on repo? Unpublish?

**Comment by jonmmease** [comment]
> Is it time to deprecate @jupyterlab/plotly-extension?

Almost. We have the release candidate of `jupyterlab-plotly` published, and we'll push out `jupyterlab-plotly@1.0.0` in a few days.  I'll ping here when that happens. Thanks for following up!

**Comment by jonmmease** [comment]
Published! Please deprecate in favor of `jupyterlab-plotly@1.0.0`. Thanks!

**Comment by gnestor** [comment]
Ok, I deprecated on npm:

```bash
$ npm deprecate @jupyterlab/plotly-extension@* "This package is being deprecated. Please use the Plotly-supported jupyterlab-plotly (https://www.npmjs.com/package/jupyterlab-plotly). See the plotly.py README for more info: https://github.com/plotly/plotly.py#jupyterlab-support-python-35"
```

**Comment by jonmmease** [comment]
Sounds great!
