### ISSUE TITLE
why  chart of the plotly code output don't displayed?

### ISSUE THREAD

**Issue by x83443647629** [jupyterlab/jupyter-renderers#217]
I've had a problem with using plotly in Jupiterlab/jupyternotebook, the chart of the code output is not properly displayed,  the code is as follows, and the jupyterlab/jupyter-plug-in has been installed 

import plotly.graph_objs as go
fig = go.Figure({
    'data':[{'type':'bar',
             'x':[1,2,3],
             'y':[1,3,2]}],
    'layout':{'title':{'text':'A Bar Chart'}}
})
fig.show()

**Comment by ptiagi** [comment]
I have the same issue. The plot doesn't show up when I run the following:
import plotly.express as px
fig = px.scatter(x=[0, 1, 2, 3, 4], y=[0, 1, 4, 9, 16])
fig.show()

I tried to run it in offline mode but that didn't help either.

**Comment by ptiagi** [comment]
My issue was resolved with proper installations given here: https://github.com/plotly/plotly.py#jupyterlab-support-python-35

**Comment by rajvijen** [comment]
@x83443647629 ,This is the reason.

[@jupyterlab/plotly-extension](https://www.npmjs.com/package/@jupyterlab/plotly-extension) is being deprecated. Please use the Plotly-supported jupyterlab-plotly. See the [plotly.py README](https://github.com/plotly/plotly.py#jupyterlab-support-python-35) for more info.

**Comment by vidartf** [comment]
Closing as answered. Thanks @rajvijen and @ptiagi !
