### ISSUE TITLE
Package into a python extension

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/jupyter-renderers#235]
Would be nice to not need npm to install these extensions.

**Comment by jtpio** [comment]
Draft PR to address this: https://github.com/jupyterlab/jupyter-renderers/pull/243

**Comment by jtpio** [comment]
This will also help remove this task in the `jupyterlab-demo` setup: https://github.com/jupyterlab/jupyterlab-demo/blob/5a5eb6bb04250b199a1cbb529e744075216a17a5/tasks.py#L52-L54
