### ISSUE TITLE
Pie charts also broken

### ISSUE THREAD

**Issue by timkpaine** [jupyterlab/jupyter-renderers#24]
Error: Invalid negative value for <rect> attribute width="-26"

**Comment by timkpaine** [comment]
Bar charts, stacked bar, histogram, etc are all broken as well, they just render as line

**Comment by dhirschfeld** [comment]
***xref:*** #22 - it sounds like the underlying bug is the same.

**Comment by gnestor** [comment]
Thanks for providing more details. I'm going to close this to move conversation to https://github.com/jupyterlab/jupyter-renderers/issues/21.

**Comment by gnestor** [comment]
I just published [@jupyterlab/plotly-extension](https://www.npmjs.com/package/@jupyterlab/plotly-extension) 0.10.0 which should resolve this issue 👍

**Comment by timkpaine** [comment]
@gnestor  awesome, thanks!
