### ISSUE TITLE
production build not happening automatically when releasing python packages

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyter-renderers#249]
When I released the last versions of the packages, I had to do clean out the js builds before starting the python release process, otherwise I was ending up with some builds that were not production builds (i.e., were not minimized, etc.). I thought that I wouldn't have to do a `git clean -dfx` before doing the python build. This would be good to look into, as right now if you don't clean, it seems you release packages that are about 2x as big because the js is not minified.

**Comment by jtpio** [comment]
Maybe first invoking the `clean:all` script: https://github.com/jupyterlab/jupyter-renderers/blob/a50d35b4ae73d2a29c36b2229b913869e51affc7/packages/fasta-extension/package.json#L41

Here: 

https://github.com/jupyterlab/jupyter-renderers/blob/a50d35b4ae73d2a29c36b2229b913869e51affc7/package.json#L8

Might be enough?
