### ISSUE TITLE
plots not appearing (but no error, and it looks like there is a result; result is invisible) with plotly in jupyter lab

### ISSUE THREAD

**Issue by tbans** [jupyterlab/jupyter-renderers#262]
labels = list(mexico.columns)[2:5]
values = mexico.iloc[0,2:5]
colors = ['coral','mediumorchid','skyblue']
fig = go.Figure(data=[go.Pie(labels=labels, values=values,  pull=[0, 0, 0.2, 0])])
fig.update_traces(hoverinfo='label+percent', textinfo='label+value', showlegend = False, textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=2)))

fig.show()

**Comment by fcollonval** [comment]
Plotly renderer is supported by Plotly directly in [that repository](https://github.com/plotly/plotly.py). Would you mind reporting the issue there?
