### ISSUE TITLE
GeoJSON: Reasoning behind disabled scrollWheelZoom?

### ISSUE THREAD

**Issue by flesser** [jupyterlab/jupyter-renderers#29]
What is the consideration behind calling `this._map.scrollWheelZoom.disable();`during map initialization?

For visualization purposes, I like to zoom in to details of the displayed geometry or zoom out to put it in a better geographic context a lot, but having to do so by clicking the +/- buttons feels very clumsy.

**Comment by gnestor** [comment]
This is an artifact of jupyterlab_geojson (which probably borrowed from nteract's [plotly-transform](https://github.com/nteract/nteract/blob/master/packages/transform-geojson/src/index.js)). I think the rationale is that it will interrupt a user scrolling through a notebook as soon as the mouse cursor is over a map output. I'm ok with removing this but would like a little more input from others.

@jasongrout @ellisonbg @rgbkrk

**Comment by rgbkrk** [comment]
The way I'd like the user experience flow to work is that if someone is active/focused inside of the output, the scroll events should be active. If they're not, they should be able to scroll through the document.

**Comment by gnestor** [comment]
Easy enough!!

```js
this._map.scrollWheelZoom.disable();
this._map.on('blur', (event) => {
  this._map.scrollWheelZoom.disable();
});
this._map.on('focus', (event) => {
  this._map.scrollWheelZoom.enable();
});
```
