### ISSUE TITLE
MathJax3-extension doesn't enable MathJax3 rendering

### ISSUE THREAD

**Issue by hfbauman22** [jupyterlab/jupyter-renderers#297]
I seem to be having difficulties getting the mathjax3-extension to work. I've tried installing it through `conda` and through the `jupyter labextension` installer. Neither seems to enable rendering with MathJax3. I have two symptoms that indicate this:

1. After rendering a LaTeX expression in a Jupyter Notebook, I right-click the rendered output and select "about MathJax". When running the Jupyter notebook "normally" with `jupyter notebook`, it indicates that it is using MathJax 2.7.9. When using the Jupyter notebook extension in Spyder, it indicates v2.7.5.
2. In both environments, I attempt to load the physics package with $$\require{physics}$$. That line runs without error, but the physics package is clearly not loaded, since running $$\dv{y}{x}$$ returns a red \dv x y, indicating what I believe to be a LaTeX compilation error.

Any suggestions, or is this a known bug? If it helps, I have jupyterlab v3.5.0 installed in the environment, as well as spyder 5.4.2 and spyder-notebook 0.4.0. Thanks!

**Comment by krassowski** [comment]
@hfbauman22 these renderers are only supported for JupyterLab and Jupyter Notebook v7+. Spyder is a separate application and you would need to contact Spyder team for help.
