### ISSUE TITLE
GeoJSON: [Proposal] Change default basemap

### ISSUE THREAD

**Issue by flesser** [jupyterlab/jupyter-renderers#30]
I found the [Carto Basemap](https://carto.com/location-data-services/basemaps/) much better suited to visualize overlayed geographical data.

It looks much cleaner (less visual clutter), has nice HiDPI support, and fits very smoothly within the overall JupyterLab theme:

![carto](https://user-images.githubusercontent.com/510681/30597268-ca0f1a8e-9d56-11e7-8040-087d992655ec.png)

Before:
![mapnik](https://user-images.githubusercontent.com/510681/30597272-cc765562-9d56-11e7-92ce-2c39466b9d9a.png)

I know this can also be archived manually by calling
```python
GeoJSON(
    data,
    url_template="https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}{r}.png",
    layer_options={
        "attribution": '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, &copy; <a href="https://carto.com/attribution">CARTO</a>'
    }
)
```
, so I'm not sure if this is the right place to put such a proposal or if it should even be scope of this repository / plugin to have a different default basemap than the very basic OSM Mapnik tiles.

**Comment by gnestor** [comment]
Hi @flesser! Thanks for sharing this I agree, I think it does pair better with the JupyterLab theme than the OSM default basemap. I think the only thing that we need to consider before switching over is the open-ness of Carto's basemaps. 

@ellisonbg What are your thoughts?

**Comment by ellisonbg** [comment]
Nice! I am in favor of this, as long as there are no copyright or licensing issues.

**Comment by mjmdavis** [comment]
The [CARTO Free Basemaps Terms of Service](https://drive.google.com/file/d/0B3OBExqwT6KJNHp3U3VUamx6U1U/view), found [here](https://carto.com/legal/) contains several clauses that give me pause.

* *"use the Services for non-commercial purposes."*
* *"immediately terminate your access if we decide in our sole discretion that your use of the Services is for a commercial purpose."*

Additionally the text on [their webpage](https://carto.com/location-data-services/basemaps/) suggests some additional constraints that I didn't find listed in the TOS:
* *"You use the basemap service for commercial purposes."*
* *"The basemap is used inside an application or website that requires payment, is private or is used for asset-tracking."*

I would consider the use of this plugin by employees of a corporate to be in violation of these terms.
* non-commercial purposes
    * By definition use of this in a company would be a commercial purpose.
* inside an application that is private
    * A jupyter lab instance could be considered a private application.
* used for asset tracking
    * Jupyter lab users would not be allowed to use this plugin for tracking assets.

**Comment by gnestor** [comment]
Thanks, @mjmdavis! 

Ok, let's just close this PR for now. If a user wants to use Carto basemap in lieu of OSM, they can do that now by simply passing `url_template` and  `layer_options` arguments to GeoJSON:

```py
from IPython.display import GeoJSON

GeoJSON(data={
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [-118.4563712, 34.0163116]
    }
}, url_template="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png", 
layer_options={
    "attribution" : '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, &copy; <a href="https://carto.com/attribution">CARTO</a>'
})
```
