### ISSUE TITLE
Plotly: height attribute ignored / overwritten

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyter-renderers#38]
In jupyterlab the plotly figure gets resized to the width of the container so e.g. when you open/collapse the side-panel the plot resizes to fit the width of the notebook without any scroll bars.

This adaptive-width behaviour is fine, *however* the height of the figure is completely ignored and appears to just be fixed.

**JupyterLab:**
![image](https://user-images.githubusercontent.com/881019/30996694-f732f9e8-a505-11e7-876f-230cfd9e6242.png)

**Jupyter Notebook:**
![image](https://user-images.githubusercontent.com/881019/30996699-0728f42e-a506-11e7-99ae-51984db750c3.png)

*Aside:* As can be seen the heatmaps do now work so thanks for fixing that @gnestor :tada:

**Comment by dhirschfeld** [comment]
***Repro notebook:***   https://anaconda.org/dhirschfeld/jupyterplotlybug/notebook

<table>
<tr>
<th><h4>JupyterLab</h4></th><th><h4>Jupyter Notebook</h4></th>
</tr>
<tr>
<td valign="top">
<img src="https://user-images.githubusercontent.com/881019/30996887-69c43eda-a507-11e7-90d6-8a6d3b528a40.png"/>
</td>
<td valign="top">
<img src="https://user-images.githubusercontent.com/881019/30996980-f1dba6b4-a507-11e7-948d-d71ecd522e51.png"/>
</td>
</tr>
</table>

**Comment by gnestor** [comment]
@dhirschfeld Thanks for catching this! I removed the CSS rule that was enforcing a fixed height of 360px in https://github.com/jupyterlab/jupyter-renderers/pull/42.

Here is the notebook that I tested against this branch (adapted to Python 3): https://gist.github.com/gnestor/661f4b4a631ad810b377a911398d8753
