### ISSUE TITLE
Plotly extension install. failed

### ISSUE THREAD

**Issue by empet** [jupyterlab/jupyter-renderers#54]
I installed json extension and it worked well, but plotly failed with the following error:

```
> webpack
fs.js:994
  binding.lstat(pathModule._makeLong(path), statValues);
              ^
Error: ENOENT: no such file or directory, lstat
```

**Comment by gnestor** [comment]
Can you try `jupyter lab clean && jupyter labextension install @jupyterlab/plotly-extension`? If you run into the same error, can you share console logs of the plotly installation, too?

**Comment by gnestor** [comment]
Closing this for now. Feel free to re-open if the issue persists.
