### ISSUE TITLE
Publish Packages

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyter-renderers#8]
It seems the packages haven't yet been published?

Is there some way to "install" the extensions from the source *without* linking?
i.e. after installing the extension I should be able to delete the source dir and the extension should still work

I'm interested because linking isn't working for me on my Windows Container.

**Comment by gnestor** [comment]
They're published! See README for installation instructions.

**Comment by dhirschfeld** [comment]
It seems the plotly extension hasn't been published? That was the one I was hoping to use!
```
C:\Jupyter\dhirschf>jupyter labextension install @jupyterlab/plotly-extension
> npm.cmd pack @jupyterlab/plotly-extension
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\bin\\nodejs\\node.exe" "C:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "pack" "@jupyterlab/plotly-extension"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code E404

npm ERR! 404 Not found : @jupyterlab/plotly-extension
npm ERR! 404
npm ERR! 404  '@jupyterlab/plotly-extension' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

**Comment by gnestor** [comment]
It will be published once https://github.com/jupyterlab/jupyter-renderers/issues/10 is resolved
