### ISSUE TITLE
Plotly: Space for plot is too small

### ISSUE THREAD

**Issue by Juanlu001** [jupyterlab/jupyter-renderers#85]
I installed Jupyterlab 0.31 and the latest version of jupyter-renderers and I'm getting too little space for the plots:

![screenshot-2018-1-11 jupyterlab](https://user-images.githubusercontent.com/316517/34841375-5fbc79cc-f708-11e7-99ed-fdaf6562c7c4.png)

However, the menu actions on the top right are there and I can even download the plot and the result looks correct:

![newplot](https://user-images.githubusercontent.com/316517/34841400-792c5f76-f708-11e7-85b0-906b4c3143af.png)

**Comment by gnestor** [comment]
I can't reproduce this with the current version of the extension and lab:

![image](https://user-images.githubusercontent.com/512354/35170448-30070c48-fd15-11e7-82cd-42ce3800c224.png)

You can try running your code against a live version of the lab beta and the current version of plotly-extension: https://hub.mybinder.org/user/jupyterlab-jupyter-renderers-emqoykxt/lab/tree/notebooks/plotly-extension.ipynb

```py
import plotly.offline
import numpy as np

data = [dict(
    visible=False,
    line=dict(color='00CED1', width=6),
    name='v ' + str(step),
    x=np.arange(0,10,0.01),
    y=np.sin(step+np.arange(0,10,0.01))
) for step in np.arange(0,5,0.1)]

data[10]['visible'] = True

fig = dict(data=data)

plotly.offline.iplot(fig)
```

You can also upgrade your local lab (`pip install jupyterlab --upgrade --pre`) and plotly-extension (`jupyter labextension install @jupyterlab/plotly-extension`).

**Comment by Juanlu001** [comment]
I updated everything and in latest Firefox I still see the cropped area, whereas in Chromium everything looks good. Not sure how it looked in Chromium before the update though.

**Comment by gnestor** [comment]
Ah, Firefox. I just submitted a PR that uses a fixed height for plotly outputs: https://github.com/jupyterlab/jupyter-renderers/pull/87

**Comment by Juanlu001** [comment]
Confirmed that it now works with current master. Thanks!

**Comment by JacoGasp** [comment]
I still have this problem with Chrome/Safari and latest version of jupyterLab and the jupyter render extension, using custom height.

Exporting the notebook to html it is ok, but in jupyter lab the cell height is not varying, partially hiding the plot.

Using
```python
data = [dict(
    visible=False,
    line=dict(color='00CED1', width=6),
    name='v ' + str(step),
    x=np.arange(0,10,0.01),
    y=np.sin(step+np.arange(0,10,0.01))
) for step in np.arange(0,5,0.1)]

data[10]['visible'] = True

fig = dict(data=data, layout=Layout(autosize=False, height=800))

plotly.offline.iplot(fig)
```
the output is

![image](https://user-images.githubusercontent.com/6513727/35977862-73b1f1cc-0ce4-11e8-8f78-2b38cd193e31.png)

**Comment by gnestor** [comment]
@JacoGasp I just pushed @jupyterlab/plotly-extension 0.14.3 which fixes this 👍

**Comment by itorralbo** [comment]
Wow! Thank you. Now works for me.

**Comment by xiaokunx** [comment]
latest package is https://www.npmjs.com/package/jupyterlab-plotly
