### ISSUE TITLE
Notebook with embedded vega-lite output doesn't show properly 

### ISSUE THREAD

**Issue by davidanthoff** [jupyterlab/jupyter-renderers#92]
I'm trying to use the built-in vega-lite support for the julia [VegaLite.jl](https://github.com/fredo-dedup/VegaLite.jl) package. Through a lot of hoops I managed to create [this](https://gist.github.com/davidanthoff/acff2966a27c9e8833a621756f8be15c) notebook file. Don't try to run the code in that notebook, that part only works if you have a whole number of unreleased branches checked out on the julia side of things.

BUT, at the end of the day, I would have expected that if this notebook file just gets opened in jupyterlab with the vega3 extension installed, that it would show the vega-lite plot. The second cell does have a data field that has the mime type ``application/vnd.vegalite.v2+json``, and inside there it does have a valid vega-lite 2 spec, so shouldn't this show the graph if I just open that file in jupyterlab?

I am suspecting that I'm doing something wrong because it also doesn't show in [nteract](https://github.com/nteract/nteract/issues/2436).

Any pointers would be greatly appreciated!

**Comment by domoritz** [comment]
Can you try to compare with https://github.com/jupyterlab/jupyter-renderers/blob/master/notebooks/vega3-extension.ipynb?

**Comment by davidanthoff** [comment]
Ah, that is super helpful! When I open that, everything looks the way it should. And there is a key difference between what I generated and that file: in my case the vega-lite spec is inside a string, whereas in the file that works the JSON from the vega-lite spec is just part of the notebook JSON. So, I just have to figure out how to get that kind of output and we might be good. I'll report back.

**Comment by davidanthoff** [comment]
Alright, just waiting for https://github.com/JuliaLang/IJulia.jl/pull/621 to be merged, and then it should all be good.

**Comment by domoritz** [comment]
:tada:

**Comment by davidanthoff** [comment]
Ok, no all working end-to-end :) Thanks for the help!

**Comment by gnestor** [comment]
I just published @jupyterlab/vega3-extension 0.14.3 with this fix 👍
